// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeplSjjIODO-5ixOWv8502Un_gPNTa0BY',
    appId: '1:333406573402:web:d97cba57cadf3dcb469963',
    messagingSenderId: '333406573402',
    projectId: 'only-chat-2026',
    authDomain: 'only-chat-2026.firebaseapp.com',
    storageBucket: 'only-chat-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmgemML2hc6rlWrzaCm3jKjo8nbzcEaV8',
    appId: '1:333406573402:android:f5239c6caf8044e3469963',
    messagingSenderId: '333406573402',
    projectId: 'only-chat-2026',
    storageBucket: 'only-chat-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRL6S5kfnhEJ7aOis6BUilNQzG_kHgSSY',
    appId: '1:333406573402:ios:c256f3461cc6a6eb469963',
    messagingSenderId: '333406573402',
    projectId: 'only-chat-2026',
    storageBucket: 'only-chat-2026.firebasestorage.app',
    iosBundleId: 'com.onlychat.onlychat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRL6S5kfnhEJ7aOis6BUilNQzG_kHgSSY',
    appId: '1:333406573402:ios:c256f3461cc6a6eb469963',
    messagingSenderId: '333406573402',
    projectId: 'only-chat-2026',
    storageBucket: 'only-chat-2026.firebasestorage.app',
    iosBundleId: 'com.onlychat.onlychat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeplSjjIODO-5ixOWv8502Un_gPNTa0BY',
    appId: '1:333406573402:web:7610bd3c8f23a9d6469963',
    messagingSenderId: '333406573402',
    projectId: 'only-chat-2026',
    authDomain: 'only-chat-2026.firebaseapp.com',
    storageBucket: 'only-chat-2026.firebasestorage.app',
  );
}
